### PR TITLE
Allow use of different case for model class name and column name 

### PR DESCRIPTION
**Pull request by iyiolapeter**
Sometimes it's helpful to be able to use different cases for the generated class names and the column names or supply own transform function in programmatic usage.

Method 1 (Current):
```typescript
metadata: {
     case:  'PASCAL',
      ...
 }
```

Method 2 (Pass an object -TransformCollection):
```typescript
metadata: {
     case: {
         model: 'PASCAL',
         column: 'LOWER'
      },
      ...
 }
```

Method 3 (Pass custom TransformFunction):
```typescript
metadata: {
     case: (value: string, type: TransformType) => {
               if(type === TransformType.MODEL){
                     // return something
               }
              // return something else
     },
      ...
 }
```

### CODE REVIEW

**Comment by spinlud** [comment]
Hi! 
Thanks for the PR, it's a good idea!

I would like to have CLI and programmatic usage as close as possible to each other, thus I was thinking to let users specify a different format for the `--case` parameter, something like this:

```shell
--case const:camel
```

where the token on the left of the colon specifies the model case and the token on the right specifies the column case.  We can update the CLI parser to handle both logics (unique case for both model and column and specific cases for each one). What do you think?

**Comment by spinlud** [comment]
Please do you mind to change the PR target branch to `develop`?

**Comment by iyiolapeter** [comment]
> Hi!
> Thanks for the PR, it's a good idea!
> 
> I would like to have CLI and programmatic usage as close as possible to each other, thus I was thinking to let users specify a different format for the `--case` parameter, something like this:
> 
> ```shell
> --case const:camel
> ```
> 
> where the token on the left of the colon specifies the model case and the token on the right specifies the column case. We can update the CLI parser to handle both logics (unique case for both model and column and specific cases for each one). What do you think?

I agree with you. Would you like me to include it in the pull request?

**Comment by spinlud** [comment]
> > Hi!
> > Thanks for the PR, it's a good idea!
> > I would like to have CLI and programmatic usage as close as possible to each other, thus I was thinking to let users specify a different format for the `--case` parameter, something like this:
> > ```shell
> > --case const:camel
> > ```
> > 
> > 
> > where the token on the left of the colon specifies the model case and the token on the right specifies the column case. We can update the CLI parser to handle both logics (unique case for both model and column and specific cases for each one). What do you think?
> 
> I agree with you. Would you like me to include it in the pull request?

I'll add it after the merge

**Pull request merged**
